#!/bin/bash
# Set permissions except on the www directory which should be world-readable
chown -R root:root /opt/ezfirewall
find /opt/ezfirewall -type d -not -path "/opt/ezfirewall/www*" -exec chmod 750 {} \;
find /opt/ezfirewall -type f -not -path "/opt/ezfirewall/www*" -exec chmod 640 {} \;
find /opt/ezfirewall/www -type d -exec chmod 755 {} \;
find /opt/ezfirewall/www -type f -exec chmod 644 {} \;
chmod 751 /opt/ezfirewall
chmod 750 /opt/ezfirewall/ezfirewall.py
chmod 644 /opt/ezfirewall/version
chmod 751 /opt/ezfirewall/bin/rsyslog-to-database.py

# Create a symlink for the ezfirewall command
if [ ! -L "/usr/local/bin/ezfirewall" ]; then
    ln -s /opt/ezfirewall/ezfirewall.py /usr/local/bin/ezfirewall
fi

# Deploy rsyslog configuration for ezfirewall
if [ -d /etc/rsyslog.d ]; then
    \cp /opt/ezfirewall/templates/nftables-rsyslog /etc/rsyslog.d/nftables.conf
    chmod 644 /etc/rsyslog.d/nftables.conf

    # Restart rsyslog if it is running
    if systemctl is-active --quiet rsyslog; then
        systemctl restart rsyslog --quiet
    fi
fi

# Deploy logrotate configuration for nftables drop logs
if [ -d /etc/logrotate.d ]; then
    \cp /opt/ezfirewall/templates/nftables-logrotate /etc/logrotate.d/nftables
    chmod 644 /etc/logrotate.d/nftables
fi
